var tr = {
	'language': 'eng',
	'shemaHeader': {
		'wheelchairFriendly': 'Stations with routes accessible for wheelchair users',
		'handicappedFriendly': 'Stations with routes accessible for people with walking difficulties',
		'luggageFriendly': 'Stations with routes accessible for people with baby-strollers'
	},
	'stationHeader': {
		'routesIn': 'Number of in-routes',
		'routesOut': 'Number of out-routes',
		'minTaper': 'Narrowest place on the routes, mm',
		'minStairways': 'Minimal number of escalators on the routes',
		'maxLiftAmount': 'Maximal number of elevators on the routes',
		'minStairs': 'Minimal stairs total length on the routes, steps',
		'avStairs': 'Average stairs total length on the routes, steps',
		'maxStairs': 'Maximum stairs total length on the routes, steps',
		'minRailsStairs': 'Minimal stairs total length on the routes when using ramps or rails, steps',
		'avRailsStairs': 'Average stairs total length on the routes when using ramps or rails, steps',
		'maxRailsStairs': 'Maximum stairs total length on the routes when using ramps or rails, steps',
		'minLiftStairs': 'Minimal stairs total length on the routes when using elevators, steps',
		'avLiftStairs': 'Average stairs total length on the routes when using elevators, steps',
		'maxLiftStairs': 'Maximum stairs total length on the routes when using elevators, steps',
	},
	'nodeHeader': {
		'totalElements': 'Number of node infrastructure elements measured',
		'stairwaysAmount': 'Number of escalators',
		'doorsAndTapersAmount': 'Number of doors',
		'minDoorAndTaperWidth': 'Minimal door width, mm',
		'turnstilesAmount': 'Number of turnstiles',
		'minturnstileWidth': 'Minimal turnstiles width, mm',
		'liftAmount': 'Number of elevators',
		'hallLevelLiftsAmount': 'Number of elevators leading to entrance hall level',
		'trainLevelLiftsAmount': 'Number of elevators leading to train platforms',
		'surfaceLevelLiftsAmount': 'Number of elevators leading to day surface',
		'minLiftWidth': 'Минимальная ширина дверей лифтов, мм',
		'pandusAmount': 'Number of ramps',
		'pandusMaxSlope': 'Maximum ramps slope, %',
		'pandusAvailableAmount': 'Number of ramps accessible for wheelchair users',
		'stairsAmount': 'Number of stairs',
		'noRailingAmount': 'Number of stairs without handrails',
		'coupleStairsAmount': 'Number of single steps',
		'railsStairsAmount': 'Number of stairs with rails',
		'minRailsWidth': 'Minimal rails width, mm',
		'maxRailsWidth': 'Maximum rails width, mm',
		'maxRailsSlope': 'Maximum rails slope, %'
	},
	'accessibilityHeader': {
		'wheelchairFriendlyRoutesIn': 'Number of in-routes accessible for wheelchair users',
		'wheelchairFriendlyRoutesOut': 'Number of out-routes accessible for wheelchair users',
		'handicappedFriendlyRoutesIn': 'Number of in-routes accessible for people with walking difficulties',
		'handicappedFriendlyRoutesOut': 'Number of out-routes accessible for people with walking difficulties',
		'luggageFriendlyRoutesIn': 'Number of in-routes accessible for people with baby-strollers',
		'luggageFriendlyRoutesOut': 'Number of out-routes accessible for people with baby-strollers'
	},
	'transferHeader': {
		'minWidth': 'Narrowest place, mm',
		'minStairs': 'Stairs total length, steps',
		'minRailsStairs': 'Stairs total length when using ramps or rails, steps',
		'minLiftStairs': 'Stairs total length when using elevators, steps',
		'stairwaysAmount': 'Number of escalators',
		'liftAmount': 'Number of elevators',
		'wheelchairFriendlyRoutes': 'Is transfer route accessible for wheelchair users?',
		'handicappedFriendlyRoutes': 'Is transfer route accessible for people with walking difficulties?',
		'luggageFriendlyRoutes': 'Is transfer route accessible for people with baby-strollers?'
	},
	'target': {
		'station': 'for station ',
		'node': 'Node ',
		'transfer': 'for transfer ',
		'metro': 'for metro system '
	},
	'booleanWords': {
		'yes': 'yes',
		'no': 'no'
	},
	'metroStatHeader': {
		'totalElements': 'Total number of infrastructure elements measured',
		'totalRoutesIn': 'Total number of in-routes',
		'totalRoutesOut': 'Total number of out-routes',
		'totalTransfers': 'Total number of transfer routes',
		'totalNodesWithTransfers': 'Total number of nodes with transfer routes',
		'totalLifts': 'Total number of elevators',
		'totalHallLevelLifts': 'Total number of elevators leading to entrance hall level',
		'totalTrainLevelLifts': 'Total number of elevators leading to train platforms',
		'totalSurfaceLevelLifts': 'Total number of elevators leading to day surface',
		'totalNodesWithLifts': 'Total number of nodes with elevators',
		'totalNodesWithHallLevelLifts': 'Total number of nodes with elevators leading to entrance hall level',
		'totalNodesWithTrainLevelLifts': 'Total number of nodes with elevators leading to train platforms',
		'totalNodesWithSurfaceLevelLifts': 'Total number of nodes with elevators leading to day surface',
		'totalPanduses': 'Total number of ramps',
		'totalPandusesAvailable': 'Total number of ramps accessible for wheelchair users',
		'totalNodesWithPanduses': 'Total number of nodes with ramps',
		'totalNodesWithPandusesAvailable': 'Total number of nodes with ramps accessible for wheelchair users',
		'totalNodesWithStairway': 'Total number of nodes with escalators',
		'totalCoupleStairs': 'Total number of single steps',
		'totalStationsWithWheelchairFriendlyRoutes': 'Total number of stations with routes accessible for wheelchair users',
		'totalWheelchairFriendlyRoutes': 'Total number of routes accessible for wheelchair users',
		'totalStationsWithHandicappedFriendlyRoutes': 'Total number of stations with routes accessible for people with walking difficulties',
		'totalHandicappedFriendlyRoutes': 'Total number of routes accessible for people with walking difficulties',
		'totalStationsWithLuggageFriendlyRoutes': 'Total number of stations with routes accessible for people with baby-strollers',
		'totalLuggageFriendlyRoutes': 'Total number of routes accessible for people with baby-strollers'
	}
}
